name: Update README

on:
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    name: crontreras1
    
    steps:
      - uses: actions/checkout@v2.3.4
        
      - uses: Readme-Workflow/recent-activity@v2.4.1
        env: 
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
